// This file was generated by executing this statement: wav2c gunEmpty48k.wav
extern uint16_t battleDroidScream48k_wav[];
#define BATTLEDROIDSCREAM48K_WAV_SAMPLE_RATE 480000
#define BATTLEDROIDSCREAM48K_WAV_BITS_PER_SAMPLE 16
#define BATTLEDROIDSCREAM48K_WAV_NUMBER_OF_SAMPLES 107069
